### ISSUE TITLE
Tech demonstration on OSX

### ISSUE THREAD

**Issue by rhaamo** [ImpalerWrG/Khazad#3]
Hi,

I've built (using netbeans, adding random .jar to project from jME3 and javatuples and lwjgl) Khazad and it seems to run.

The only problem was

```
Windows EXE Creation
/Users/dashie/hack/Khazad-0.2.1/nbproject/launch4j-impl.xml:6: taskdef class net.sf.launch4j.ant.Launch4jTask cannot be found
 using the classloader AntClassLoader[]
BUILD FAILED (total time: 29 seconds)
```
Well i'm on a mac, .app was built successfully and i dont care personally for the windows release :D

So what can be done actually in this tech demo ?

Screenshot of what i have : (i can zoom, move map, select a region, select single bloc, and dig/build doesn't do anything)
![Imgur](http://i.imgur.com/0n6sB2j.png)

**Comment by ImpalerWrG** [comment]
Are you not seeing the (terribly ugly programmer art) dwarf models?  100 should be placed on the map and run around between randomly selected points doing pathfinding.  They would also do the digging out of designated areas, though this is currently very buggy.  The upper right contains the time rate controls, the game starts paused so nothing will happen until you start time passing.  I should probably get some kind of Tutorial going even if it is just some basic text displayed on a window at start up.

The failure to build the Windows release is likely due to use of netbeans rather then JME, the Launch4jTask seems to be a cross-platform application launching library http://launch4j.sourceforge.net/docs.html perhaps netbeans just doesn't come with it.  As this dose not seem to be a barrier for you I'm inclined to ignore it for now as it would be very hard for me to figure out with both a different OS and IDE between me and reproducing the error.

BTW you r frame rate seems very low, I generally get 60-80 frames per second even when viewing the whole map and running time at maximum.  What kind of system are you running on?

**Comment by ImpalerWrG** [comment]
Thx for compiling and trying out Khazad, may I ask how you found out about
the project and what experience you have with similar types of games?  Are
you interested in doing some coding and if so what particular type or area?

**Comment by rhaamo** [comment]
I've re-started it and i have seen the dwarfs, digging seems to dig, build, well, i can't select area no more so, i don't know.

For the IDE, JME is the full SDK of jMonkeyEngine ?

For the framerate i think that the screenshot tool (skitch) messed a bit, and system load doesn't helped.
When restarting it today i got ~58/60 fps.

If i remember correctly i've found it using github search for "dwarf fortress" a long time ago and subscribed to this repo, i'm not a java developper but i can debug/build and test on Mac OSX and Linux actually.
